---
- file: path=/root/couchpotato/config/ state=directory
- copy: src=config.ini dest=/root/couchpotato/config/config.ini

- name: Create a Couchpotato container
  docker_container:
    name: couchpotato
    image: linuxserver/couchpotato
    volumes:
      - "/root/couchpotato/config:/config"
      - "/root/local/movies:/movies"
      - "/root/downloads:/downloads"
    links:
      - transmission
    ports:
      - "5050:5050"
    env:
      PUID: "{{PUID}}"
      GUID: "{{GUID}}"
      TZ: "{{TZ}}"

- ufw: src="{{ipify_public_ip}}" port=5050 rule=allow