---
- name: Create a Couchpotato container
  docker_container:
    name: couchpotato
    image: linuxserver/couchpotato
    volumes:
      - "/home/root/couchpotato/config:/config"
      - "/home/root/movies:/movies"
      - "/home/root/downloads:/downloads"
    ports:
      - "5050:5050"
    env:
      PUID: "{{PUID}}"
      GUID: "{{GUID}}"