---
- apt: name={{item}}
  with_items:
    - python3
    - python3-appdirs
    - python3-dateutil
    - python3-requests
    - python3-sqlalchemy
    - python3-pip

- pip: name="git+https://github.com/yadayada/acd_cli.git" executable=pip3 editable=false

- file: path=~/acd state=directory

- copy: src=oauth_data dest=~/.cache/acd_cli/oauth_data
- name: sync up ACD
  shell: acd_cli sync

- command: mountpoint -q ~/acd
  register: volume_stat
  failed_when: False
  changed_when: False

- name: Mount CloudDrive to ~/acd
  shell: acd_cli mount ~/acd
  when: volume_stat.rc != 0

- shell: acd_cli mkdir /{{item}}
  with_items:
    - movies
    - tvshows
  args:
    creates: ~/acd/{{item}}

- name: schedule ACD uploads
  cron: job="acd_cli upload /root/local/{{item}} /{{item}} -rsf" special_time=daily
  with_items:
    - movies
    - tvshows
