---
- name: Create a Plex container
  docker_container:
    name: plex
    image: linuxserver/plex
    volumes:
      - "/root/plex/config:/config"
      - "/root/tvshows:/data/tvshows"
      - "/root/movies:/data/movies"
      - "/root/transcoding:/transcoding"
    network_mode: host
    env:
      PUID: "{{PUID}}"
      GUID: "{{GUID}}"

- name: Allow remote access
  ufw: port={{item}} rule=allow
  with_items:
    - 32400
    - 22
