---
- name: Create a Plex container
  docker_container:
    name: plex
    image: plexinc/pms-docker
    volumes:
      - "/root/plex/config:/config"
      - "/root/tvshows:/data/tvshows"
      - "/root/movies:/data/movies"
      - "/root/transcoding:/transcoding"
    ports:
      - "32400:32400/tcp"
    env:
      PUID: "{{PUID}}"
      GUID: "{{GUID}}"
      TZ: "{{TZ}}"
      ADVERTISE_IP: "{{ansible_default_ipv4.address}}"
    hostname: "{{PLEX_HOSTNAME}}"

- name: Allow remote access
  ufw: port={{item}} rule=allow
  with_items:
    - 32400
