---
- name: Create a Sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    volumes:
      - "/root/sonarr/config:/config"
      - "/root/local/tvshows:/tv"
      - "/root/downloads:/downloads"
    links:
      - transmission
    ports:
      - "8989:8989"
    env:
      PUID: "{{PUID}}"
      GUID: "{{GUID}}"

- ufw: src="{{ipify_public_ip}}" port=8989 rule=allow
