---
- apt: name={{item}}
  with_items:
    - curl
    - git
    - htop
    - python-pip
    - vim
    - wget

- name: Obtain local IP address
  ipify_facts:
  connection: local
  become: False

- ufw: port=ssh rule=allow
- ufw: state=enabled policy=deny

- include: mounts.yml